# FIXME: This should be frozen!
channels:
  - conda-forge
  - defaults
  - conda-forge/label/broken
dependencies:
  - ipywidgets==7.5.1
  - jupyterlab==1.2.6
  - jupyterhub-singleuser==1.1.0
  - nbconvert==5.6.1
  - notebook==6.0.3
